apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: httpd-http-scaledobject
  namespace: default
spec:
  hosts:
    - httpd.local
  scaleTargetRef:
    name: httpd-deployment
    kind: Deployment
    apiVersion: apps/v1
    service: httpd-service
    port: 80
  replicas:
    min: 0
    max: 10
  scalingMetric:
    concurrency:
      targetValue: 10  # Target number of concurrent requests
  scaledownPeriod: 5  # No cooldown period

