version: '3.8'

networks:
  gateway:
    driver: overlay

services:
  webserver:
    image: webserver:latest
    # hostname: $HOSTNAME
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
    networks:
      - gateway


  prometheus:
    image: prom/prometheus:v2.48.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - gateway
