version: '3.8'

networks:
  gateway:

services:
  webserver:
    image: webserver:latest
    hostname: $HOSTNAME
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - gateway


  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831"
      - "16686:16686"
    networks:
      - gateway

