all:
  hosts:
    node1:
      ansible_host: 192.168.1.3
      ip: 192.168.1.3
      access_ip: 192.168.1.3
    node2:
      ansible_host: 192.168.1.4
      ip: 192.168.1.4
      access_ip: 192.168.1.4
    node3:
      ansible_host: 192.168.1.5
      ip: 192.168.1.5
      access_ip: 192.168.1.5
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
