---
- name: Copy fix-dns.sh to remote hosts
  copy:
    src: fix-dns.sh
    dest: /usr/local/bin/fix-dns.sh
    mode: '0755'

- name: Run fix-dns.sh
  command: /usr/local/bin/fix-dns.sh

- name: Reboot the machine
  ansible.builtin.reboot:
    msg: "Rebooting after DNS fix script execution"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
