---
- name: Copy fix-dns.sh to remote hosts
  copy:
    src: fix-dns.sh
    dest: /usr/local/bin/fix-dns.sh
    mode: '0755'

- name: Run fix-dns.sh
  command: /usr/local/bin/fix-dns.sh

# doesn't work, to fix. cloud-init fedora doesn't let you edit /etc/hosts
- name: Update /etc/hosts with custom entries
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.host }}"
    regexp: "^{{ item.ip }}\\s+{{ item.host }}"
    state: present
    create: no
    backup: yes
  loop:
    - { ip: "192.168.2.3", host: "monitoring" }
    - { ip: "192.168.2.4", host: "swarm-vm1" }
    - { ip: "192.168.2.5", host: "swarm-vm2" }
    - { ip: "192.168.2.6", host: "swarm-vm3" }

- name: Reboot the machine
  ansible.builtin.reboot:
    msg: "Rebooting after DNS fix script execution"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
