global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'swarm_nodes'
    static_configs:
      - targets:
        - '192.168.2.4:8081'
        - '192.168.2.5:8081'
        - '192.168.2.6:8081'

