- name: Install Docker on all nodes
  hosts: all
  become: true
  roles:
    - fix_dns
    - docker

- name: Init Docker Swarm on Manager Node
  hosts: swarm_manager
  become: true
  roles:
    - swarm_manager

- name: Join Docker Swarm on Worker Nodes
  hosts: swarm_worker
  become: true
  roles:
    - swarm_worker

- name: Setup Prom/Grafana
  hosts: monitoring
  roles:
    - setup_promgraf

- name: Setup cadvisor
  hosts:
    - swarm_worker
    - swarm_manager
  roles:
    - setup_cadvisor
